# This file is used to define all the services that make up your application.
# In this case, we only need a database service.
services:
  taskly-db.adria:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: adria
      MYSQL_DATABASE: virtEarth
      MYSQL_USER: adria
      MYSQL_PASSWORD: adria
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
